channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy
  - pip
  - websockify
  - paraview
  - pip:
      - git+https://github.com/SofianeB/jupyter-remote-desktop-proxy.git
      - git+https://github.com/Kitware/ipyparaview.git
